name: ditonton
description: Movie and TV discovery from TMDB API.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  core:
    path: core
  movie:
    path: movie
  television:
    path: television
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
