name: ditonton
description: Movie and TV discovery from TMDB API.

publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  core:
    path: packages/core
  movie:
    path: packages/movie
  television:
    path: packages/television
  get_it: ^7.2.0
  firebase_core: ^2.1.0
  firebase_crashlytics: ^3.0.2
  firebase_analytics: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
