name: core
description: Core module for ditonton app.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  get_it: ^7.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.4
  freezed: ^2.2.0

flutter:
  assets:
    - certificates/
    