name: movie
description: Movie module for ditonton app.
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  sqflite: ^2.0.0+3
  http: ^0.13.3
  cached_network_image: ^3.2.2
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.1.0
  freezed: ^2.2.0
