name: television
description: Television module for ditonton app.
version: 0.0.1
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  core:
    path: ../core
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.2.2
  freezed_annotation: ^2.2.0
  sqflite: ^2.1.0+1
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.4
  freezed: ^2.2.0
  mockito: ^5.3.2
  bloc_test: ^9.1.0
